# Site settings
title: SWISS MOCEAN
email: ""
description: "Swiss Mocean"
url: "https://swissmocean.github.io"
baseurl: "/swissmocean"
facebook_username: "swissmocean"
instagram_username: "swissmocean"
share: true

# Owner/author information
owner:
  name:   swissmocean
  avatar: avatar.png
  favicon: favicon.ico
  info: Official website for Swiss Mocean

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments :
  provider : Facebook Comments

# Internal nav
nav:
  - NEWS: "https://swissmocean.github.io/swissmocean/news/"
  - FAQ: "https://swissmocean.github.io/swissmocean/faq/"
  - STORY: "https://swissmocean.github.io/swissmocean/story/"
  - GALLERIE: "https://swissmocean.github.io/swissmocean/gallerie/"
  - SUPPORT: "https://swissmocean.github.io/swissmocean/support/"
  - PR&AumlSENTATIONEN: "https://swissmocean.github.io/swissmocean/praesentationen/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
